### ISSUE TITLE
Check if following endpoints are used anywhere

### ISSUE THREAD

**Issue by IgorBalog-Eng** [Engineering-Research-and-Development/true-connector-basic_data_app#44]
FileSenderResource  
/requireandsavefile
/requirefile
/artifactRequestMessage

IncomingDataAppResource 
/incoming-data-app/dataAppIncomingMessageReceiver
/incoming-data-app/postMultipartMessage
/incoming-data-app/dataAppIncomingMessageSender
/incoming-data-app/dataAppIncomingMessage

If not used anywhere, delete all code related with them.

**Comment by marest94** [comment]
Issue estimation breakdown:

- Run and test both flows (REST and WSS) - 20 minutes
