### ISSUE TITLE
Message Handler for WSS flow

### ISSUE THREAD

**Issue by IgorBalog-Eng** [Engineering-Research-and-Development/true-connector-basic_data_app#50]
Apply same logic to use message handlers we created in WSS flow
Change handlers to be constructor injection instead field injection; update tests accordingly (avoid using ReflectionUtil to set fields)

Also in tests, use following, where checking the content of the responseHandlerMap (already available constants)
responseMap.get(DataAppMessageHandler.HEADER);
responseMap.get(DataAppMessageHandler.PAYLOAD);

**Comment by marest94** [comment]
Issue estimation breakdown:

- Documentation exploring and setting up Data App to use WSS (1.5h)
- Testing current WSS flow, and exploring controllers, services, etc. (2h)
- Refactor existing controllers, services, etc. in order to use message handlers (15h)
- Writing tests for new logic (4h)
